config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :salas
  resources :doctors

  root 'home#index'


  #root :to => 'devise/sessions#create'
  #get '/admins/sign_in', to: 'devise/sessions#create', as: 'login'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
end

app/models/sala.rb
class Sala < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:cedula, :nombre, :telefono)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/salas_controller.rb
class SalasController < ApplicationController
  before_action :set_sala, only: [:show, :edit, :update, :destroy]

  # GET /salas
  # GET /salas.json
  def index
    @salas = Sala.all
  end

  # GET /salas/1
  # GET /salas/1.json
  def show
  end

  # GET /salas/new
  def new
    @sala = Sala.new
  end

  # GET /salas/1/edit
  def edit
  end

  # POST /salas
  # POST /salas.json
  def create
    @sala = Sala.new(sala_params)

    respond_to do |format|
      if @sala.save
        format.html { redirect_to @sala, notice: 'Sala was successfully created.' }
        format.json { render :show, status: :created, location: @sala }
      else
        format.html { render :new }
        format.json { render json: @sala.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salas/1
  # PATCH/PUT /salas/1.json
  def update
    respond_to do |format|
      if @sala.update(sala_params)
        format.html { redirect_to @sala, notice: 'Sala was successfully updated.' }
        format.json { render :show, status: :ok, location: @sala }
      else
        format.html { render :edit }
        format.json { render json: @sala.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salas/1
  # DELETE /salas/1.json
  def destroy
    @sala.destroy
    respond_to do |format|
      format.html { redirect_to salas_url, notice: 'Sala was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sala
      @sala = Sala.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sala_params
      params.require(:sala).permit(:numero, :disponibilidad)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/salas_helper.rb
module SalasHelper
end

app/views/doctors/_form.html.erb
<%= form_for(doctor) do |f| %>
    <% if doctor.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

          <ul>
            <% doctor.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :cedula %>
      <%= f.text_field :cedula %>
    </div>

    <div class="field">
      <%= f.label :nombre %>
      <%= f.text_field :nombre %>
    </div>

    <div class="field">
      <%= f.label :telefono %>
      <%= f.text_field :telefono %>
    </div>

    <div class="actions">
      <%= f.submit :class => "btn btn-primary" %>
    </div>

<% end %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>


<div class="well">
  <div class="row">
    <div class="col-sm-3"> <%= image_tag("Logo.JPG", size: "250x100") %> </div>
    <div class="col-sm-7"> <h1>Lista de Cirujanos</h1> </div>
  </div>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Cedula</th>
      <th>Telefono</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.cedula %></td>
        <td><%= doctor.nombre %></td>
        <td><%= doctor.telefono %></td>
        <td><%= link_to 'Show', doctor, class: "btn btn-success" %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path, class: "btn btn-primary" %>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<div class="well">

  <div class="row">
    <div class="col-sm-4">
      <%= image_tag("logoWMC.png") %>
    </div>
    <div class="col-sm-4">
      <p id="notice"><%= notice %></p>
      <p>
        <strong>Nombre:</strong>
        <%= @doctor.nombre %>
      </p>
      <p>
        <strong>Cedula:</strong>
        <%= @doctor.cedula %>
      </p>
      <p>
        <strong>Telefono:</strong>
        <%= @doctor.telefono %>
      </p>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_doctor_path(@doctor), class: "btn btn-primary" %> |
<%= link_to 'Back', doctors_path, class: "btn btn-primary" %>

app/views/home/index.html.erb
<div id="scheduler_here" class="dhx_cal_container" style='width:100%; height:800px;'>
  <div class="dhx_cal_navline">
    <div class="dhx_cal_prev_button">&nbsp;</div>
    <div class="dhx_cal_next_button">&nbsp;</div>
    <div class="dhx_cal_today_button"></div>
    <div class="dhx_cal_date"></div>
    <div class="dhx_cal_tab" name="day_tab" style="right:204px;"></div>
    <div class="dhx_cal_tab" name="week_tab" style="right:140px;"></div>
    <div class="dhx_cal_tab" name="month_tab" style="right:76px;"></div>
  </div>

  <div class="dhx_cal_header"> </div>
  <div class="dhx_cal_data"> </div>
</div>

<script>
  scheduler.init("scheduler_here");
</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-in">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="http://worldmedicalcenter.com.co/es">WORLD MEDICAL CENTER</a>
    </div>

    <ul class="nav navbar-nav">
      <!--<li class="active"><a href="#">Home</a></li>-->
      <li class="active"> <%= link_to "Home", root_path %></li>

      <li> <%= link_to "Lista de Cirujanos",  doctors_path  %> </li>

      <li> <%= link_to "Lista de Salas",  salas_path  %> </li>

    </ul>


    <ul class="nav navbar-nav navbar-right">
      <ul class = "brand"> <%= image_tag("logoWMC.png") %> </ul>
    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>World Medical Center</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'dhtmlxscheduler', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'dhtmlxscheduler', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
  </head>


  <body>
    <%= render 'layouts/header' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/salas/_form.html.erb
<%= form_for(sala) do |f| %>
  <% if sala.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sala.errors.count, "error") %> prohibited this sala from being saved:</h2>

      <ul>
      <% sala.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numero %>
    <%= f.number_field :numero %>
  </div>

  <div class="field">
    <%= f.label :disponibilidad %>
    <%= f.check_box :disponibilidad %>
  </div>

  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/salas/edit.html.erb
<h1>Editing Sala</h1>

<%= render 'form', sala: @sala %>

<%= link_to 'Show', @sala %> |
<%= link_to 'Back', salas_path %>

app/views/salas/index.html.erb
<p id="notice"><%= notice %></p>

<div class="well">
  <div class="row">
    <div class="col-sm-3"> <%= image_tag("Logo.JPG", size: "250x100") %> </div>
    <div class="col-sm-7"> <h1>Lista de Salas</h1> </div>
  </div>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Numero</th>
      <th>Disponibilidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @salas.each do |sala| %>
      <tr>
        <td><%= sala.numero %></td>
        <td><%= sala.disponibilidad %></td>
        <td><%= link_to 'Show', sala, class: "btn btn-success" %></td>
        <td><%= link_to 'Edit', edit_sala_path(sala), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', sala, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sala', new_sala_path, class: "btn btn-primary" %>

app/views/salas/new.html.erb
<h1>New Sala</h1>

<%= render 'form', sala: @sala %>

<%= link_to 'Back', salas_path %>

app/views/salas/show.html.erb
<div class="well">

  <div class="row">
    <div class="col-lg-4">
      <%= image_tag("logoWMC.png")%>
    </div>
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Numero:</strong>
      <%= @sala.numero %>
    </p>

    <p>
      <strong>Disponibilidad:</strong>
      <%= @sala.disponibilidad %>
    </p>

  </div>

  <%= link_to 'Edit', edit_sala_path(@sala), class: "btn btn-primary" %> |
  <%= link_to 'Back', salas_path , class: "btn btn-primary" %>
</div>